### ISSUE TITLE
Implementation for OnUnlockGenerator

### ISSUE THREAD

**Issue by SillySoon** [SrLicht/RemoteKeycard#3]
Im sadly not able to code this my self because I'm to stupid to clone the repo and help coding it, but this might be a good Idea :)

**Comment by SrLicht** [comment]
Because the NWAPI PlayerUnlockGeneratore event is executed when a player has a Keycard to unlock a generator, I need an Event that is PlayerInteractGenerator which I already did a PullRequest in NWAPI (https://github.com/northwood-studios/NwPluginAPI/commit/648f60e1ff3b389b56f977211eefdf0fc6804113) when NWAPI is updated to Release 6 I will be able to do this
